kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-rolebinding
  namespace: final
subjects:
- kind: ServiceAccount
  name: clo-835
  apiGroup: ""
roleRef:
  kind: Role
  name: pod-writer
  apiGroup: rbac.authorization.k8s.io