apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-mysql
  namespace: final
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp-mysql
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 2